{"uid":"35d142034f82d4d","name":"test_edit_account_field_unknow","fullName":"test.Cuentas.test_edit_account#test_edit_account_field_unknow","historyId":"556de1231d9bca46362a6c04705654b1","time":{"start":1728686314148,"stop":1728686314149,"duration":1},"status":"skipped","statusMessage":"XFAIL This test case is expected to fail due to known issue.\n\nTypeError: create_account_data() got an unexpected keyword argument 'test'","statusTrace":"setup_edit_account = ({'Espo-Authorization': 'YWRtaW46NjI0MjkyNTU=', 'X-Api-Key': 'f542db99f09e823eeb14cd558f104fef'}, {'assignedUserId': '...', 'assignedUserName': 'Admin', 'billingAddressCity': 'East Emily', 'billingAddressCountry': 'Wallis and Futuna', ...})\n\n    @pytest.mark.regression\n    @pytest.mark.functional\n    @pytest.mark.xfail(reason=\"This test case is expected to fail due to known issue.\", condition=True)\n    def test_edit_account_field_unknow(setup_edit_account):\n        headers, account = setup_edit_account\n>       data = create_account_data(name=\"prueba nueva\", billingAddressCity=\"prueba\",\n                                   billingAddressCountry=\"prueba\",\n                                   billingAddressPostalCode=\"prueba\",\n                                   billingAddressState=\"prueba\", test=\"test\",\n                                   billingAddressStreet=\"prueba\",\n                                   description=\"prueba\", emailAddress=\"prueba@prueba.com\",\n                                   industry=\"Architecture\", phoneNumber=\"+15555555555\",\n                                   shippingAddressCity=\"prueba\",\n                                   shippingAddressCountry=\"prueba\",\n                                   shippingAddressPostalCode=\"prueba\",\n                                   shippingAddressState=\"prueba\",\n                                   shippingAddressStreet=\"prueba\", type=\"Customer\",\n                                   website=\"prueba.com\")\nE       TypeError: create_account_data() got an unexpected keyword argument 'test'\n\ntest/Cuentas/test_edit_account.py:61: TypeError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1728686292858,"stop":1728686292859,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"get_headers","time":{"start":1728686292859,"stop":1728686292859,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_edit_account","time":{"start":1728686313927,"stop":1728686314148,"duration":221},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"afterStages":[{"name":"setup_edit_account::0","time":{"start":1728686314153,"stop":1728686314316,"duration":163},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"tag","value":"@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"},{"name":"tag","value":"functional"},{"name":"tag","value":"regression"},{"name":"parentSuite","value":"test.Cuentas"},{"name":"suite","value":"test_edit_account"},{"name":"host","value":"fv-az2028-648"},{"name":"thread","value":"2100-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test.Cuentas.test_edit_account"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["functional","regression","@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"]},"source":"35d142034f82d4d.json","parameterValues":[]}