{"uid":"7b39794d50d46d23","name":"test_add_account_website_invalid","fullName":"test.Cuentas.test_add_account#test_add_account_website_invalid","historyId":"5d3d4da3b201b15e7ac87b0b0d7de95f","time":{"start":1726781452105,"stop":1726781452279,"duration":174},"status":"passed","statusMessage":"XPASS This test case is expected to fail due to known issue.","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"get_headers","time":{"start":1726781434606,"stop":1726781434606,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_add_account","time":{"start":1726781452105,"stop":1726781452105,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"afterStages":[{"name":"setup_add_account::0","time":{"start":1726781452280,"stop":1726781452280,"duration":0},"status":"broken","statusMessage":"KeyError: 'id'\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n  File \"/home/runner/work/espo-automation-final/espo-automation-final/test/Cuentas/conftest.py\", line 41, in setup_add_account\n    AccountCall().delete(headers, account['id'])\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"labels":[{"name":"tag","value":"@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"},{"name":"tag","value":"functional"},{"name":"tag","value":"smoke"},{"name":"parentSuite","value":"test.Cuentas"},{"name":"suite","value":"test_add_account"},{"name":"host","value":"fv-az2036-179"},{"name":"thread","value":"2098-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test.Cuentas.test_add_account"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["functional","smoke","@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"]},"source":"7b39794d50d46d23.json","parameterValues":[]}