{"uid":"7c14b168a2a7a2bc","name":"test_edit_contact_address_invalid","fullName":"test.Contactos.test_edit_contact#test_edit_contact_address_invalid","historyId":"28de162ccc1dbd537b5441ed94667d8e","time":{"start":1728601263632,"stop":1728601263851,"duration":219},"status":"skipped","statusMessage":"XFAIL This test case is expected to fail due to known issue.\n\nAssertionError","statusTrace":"setup_edit_contact = ({'Espo-Authorization': 'YWRtaW46NjI0MjkyNTU=', 'X-Api-Key': 'f542db99f09e823eeb14cd558f104fef'}, {'accountIsInactive': None, 'accountName': None, 'accountsColumns': {}, 'accountsIds': [], ...})\n\n    @pytest.mark.regression\n    @pytest.mark.functional\n    @pytest.mark.xfail(reason=\"This test case is expected to fail due to known issue.\", condition=True)\n    def test_edit_contact_address_invalid(setup_edit_contact):\n        headers, contact = setup_edit_contact\n        data = create_contact_data(salutationName=\"Ms.\", firstName=\"Mike\",\n                                                             lastName=\"Towel\",\n                                                             emailAddress=\"one@on.as\",\n                                                             phoneNumber=\"+17945654564\",\n                                                             addressPostalCode=\"0000\", addressStreet=\"452345234$&/$%$%&/$%&($%&/··\",\n                                                             addressState=\"none\", addressCity=\"none\", addressCountry=\"none\",\n                                                             description=\"prueba\")\n        response = EspocrmRequest().put(EndpointContacts.view(contact['id']), headers, data)\n>       AssertionStatusCode().assert_status_code_400(response)\n\ntest/Contactos/test_edit_contact.py:114: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [200]>\n\n    @staticmethod\n    def assert_status_code_400(response):\n>       assert response.status_code == 400\nE       AssertionError\n\nsrc/assertions/status_code_assertions.py:19: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1728601253282,"stop":1728601253283,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"get_headers","time":{"start":1728601253283,"stop":1728601253283,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_edit_contact","time":{"start":1728601263407,"stop":1728601263631,"duration":224},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"afterStages":[{"name":"setup_edit_contact::0","time":{"start":1728601263855,"stop":1728601264089,"duration":234},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"tag","value":"@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"},{"name":"tag","value":"functional"},{"name":"tag","value":"regression"},{"name":"parentSuite","value":"test.Contactos"},{"name":"suite","value":"test_edit_contact"},{"name":"host","value":"fv-az1432-961"},{"name":"thread","value":"2163-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test.Contactos.test_edit_contact"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["functional","regression","@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"]},"source":"7c14b168a2a7a2bc.json","parameterValues":[]}