{"uid":"d04df9bec0965779","name":"test_edit_account_field_unknow","fullName":"test.Cuentas.test_edit_account#test_edit_account_field_unknow","historyId":"556de1231d9bca46362a6c04705654b1","time":{"start":1726781453627,"stop":1726781453627,"duration":0},"status":"skipped","statusMessage":"XFAIL This test case is expected to fail due to known issue.\n\nTypeError: PayloadAccount.build_payload_add_account() got an unexpected keyword argument 'test'","statusTrace":"setup_edit_account = ({'Espo-Authorization': 'YWRtaW46ODAwNDkwNTM=', 'X-Api-Key': '4c29fe9482f3bccb7ac0a7d04015a2e7'}, [{'assignedUserId': None, 'assignedUserName': None, 'billingAddressCity': None, 'billingAddressCountry': None, ...}])\n\n    @pytest.mark.regression\n    @pytest.mark.functional\n    @pytest.mark.xfail(reason=\"This test case is expected to fail due to known issue.\", condition=True)\n    def test_edit_account_field_unknow(setup_edit_account):\n        headers, account = setup_edit_account\n>       payload_account = PayloadAccount().build_payload_add_account(name=\"prueba nueva\", billingAddressCity=\"prueba\",\n                                                                     billingAddressCountry=\"prueba\",\n                                                                     billingAddressPostalCode=\"prueba\",\n                                                                     billingAddressState=\"prueba\", test=\"test\",\n                                                                     billingAddressStreet=\"prueba\",\n                                                                     description=\"prueba\", emailAddress=\"prueba@prueba.com\",\n                                                                     industry=\"Architecture\", phoneNumber=\"+15555555555\",\n                                                                     shippingAddressCity=\"prueba\",\n                                                                     shippingAddressCountry=\"prueba\",\n                                                                     shippingAddressPostalCode=\"prueba\",\n                                                                     shippingAddressState=\"prueba\",\n                                                                     shippingAddressStreet=\"prueba\", type=\"Customer\",\n                                                                     website=\"prueba.com\")\nE       TypeError: PayloadAccount.build_payload_add_account() got an unexpected keyword argument 'test'\n\ntest/Cuentas/test_edit_account.py:60: TypeError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"get_headers","time":{"start":1726781434606,"stop":1726781434606,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_edit_account","time":{"start":1726781453405,"stop":1726781453626,"duration":221},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"afterStages":[{"name":"setup_edit_account::0","time":{"start":1726781453632,"stop":1726781453632,"duration":0},"status":"broken","statusMessage":"TypeError: list indices must be integers or slices, not str\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n  File \"/home/runner/work/espo-automation-final/espo-automation-final/test/Cuentas/conftest.py\", line 58, in setup_edit_account\n    AccountCall().delete(headers, account['id'])\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"labels":[{"name":"tag","value":"@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"},{"name":"tag","value":"functional"},{"name":"tag","value":"regression"},{"name":"parentSuite","value":"test.Cuentas"},{"name":"suite","value":"test_edit_account"},{"name":"host","value":"fv-az2036-179"},{"name":"thread","value":"2098-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test.Cuentas.test_edit_account"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["functional","regression","@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"]},"source":"d04df9bec0965779.json","parameterValues":[]}